config/routes.rb
Rails.application.routes.draw do
  resources :lists
  namespace :api, defaults: {format: 'json'} do
    get '/lists' => 'lists#index'
    get '/lists/:id' => 'lists#show'
    get '/lists/?:title' => 'lists#title'
  end
  get '/send_email' => "lists#send_email"
  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
before_save :vat_value
validates :product_id, uniqueness: true 
validates_numericality_of :price, :on => :create
validates :title,:description,:text, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
has_attached_file :photo, 
styles: { thumb: "100x100>" }#, default_url: "/images/:style/missing.png",
#path: ":rails_root/public/images/:id/:filename",
# url: "/images/:id/:filename"

do_not_validate_attachment_file_type :photo
  # validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
	def vat_value
		self.price *=  self.quantity
		self.vat = (self.price) * 0.2
		self.total = (self.price) + self.vat
	end

def self.search(search)
  if search
    where('title LIKE ?', "%#{search}%")
  else
    all
  end
end


before_create :set_product_id
def set_product_id
	if List.count <1
		self.product_id = "PDCT-1001"
	else
	last_product_id = List.last.product_id.split('-').last.to_i + 1
	self.product_id = "PDCT-" + "#{last_product_id.to_s}"
	end
end
end

app/controllers/api/lists_controller.rb
module Api

class ListsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    # respond_to do |format|
    # format.html
    # format.js   
    # format.json { head :no_content }
    # end
    render json: {list: @lists}
  end
  # GET /lists/1
  # GET /lists/1.json
  def show
    # render 'new'
    render json: {list: @list}
  end
  def title
    @list = List.where(:title => params[:title])
    render json: {list: @list}

  end
  # GET /lists/new
  def new
    @list = List.new
  end

  def send_email
    @lists = List.all
    ExampleMailer.sent_product(@lists).deliver_now  
    # redirect_to lists_path
    render :index
  end
  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.photo = nil
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description, :text, :price, :quantity, :photo, :vat, :total, :product_id )
    end

  def sort_column
    List.column_names.include?(params[:sort]) ? params[:sort] : "title" 
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 3, :page => params[:page])
    respond_to do |format|
    format.html
    format.js   
    format.json { head :no_content }
    end
  end
  # GET /lists/1
  # GET /lists/1.json
  def show
    # render 'new'
  end
  # GET /lists/new
  def new
    @list = List.new
  end

  def send_email
    @lists = List.all
    ExampleMailer.sent_product(@lists).deliver_now  
    # redirect_to lists_path
    render :index
  end
  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.photo = nil
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description, :text, :price, :quantity, :photo, :vat, :total, :product_id )
    end

  def sort_column
    List.column_names.include?(params[:sort]) ? params[:sort] : "title" 
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
# def paginate(collection, params= {})
#     will_paginate collection, params.merge(:renderer => RemoteLinkPaginationHelper::LinkRenderer)

# end
def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction ==  "asc" ? "desc" : "asc" 
  link_to title, params.merge(:sort => column, :direction => direction,  :page => nil), {:class => css_class}
end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/remote_link_pagination_helper.rb
module RemoteLinkPaginationHelper
class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    def link(text, target, attributes = {})
      attributes['data-remote'] = true
      super
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<div class="row">
<div class="col-md-12">
<%= yield %>
</div>
</div>
</div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
   <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>


  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div class="field" >
    <%=  f.hidden_field :vat %>
  </div>
  <div class="field">
    <%= f.hidden_field :total %>
  </div>
  <div class="field">
    <%= f.hidden_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_lists.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<table class="table">
  <thead>
    <tr>
      <th><%= sortable "title" %></th>
      <th><%= sortable "description" %></th>
      <th><%= sortable "text" %></th>
      <th><%= sortable "price" %></th>
      <th><%= sortable "quantity" %></th>
      <th><%= sortable "photo" %></th>
      <th><%= sortable "vat" %></th>
      <th><%= sortable "total" %></th>
      <th><%= sortable "product_id" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.description %></td>
        <td><%= list.text %></td>
        <td><%= list.price %></td>
        <td><%= list.quantity %></td>
        <td><%= image_tag list.photo %></td>
        <td><%= list.vat %></td>
        <td><%= list.total %></td>
        <td><%= list.product_id %></td>
	<td><%= link_to 'Show', list, method: :get, :remote => true, class: 'show_list btn btn-primary btn-xs' %></td>

	<td><%= link_to 'Edit', edit_list_path(list),   class: 'btn btn-info btn-xs' %></td>

	<td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, 
        :remote => true, :class => 'delete_list btn btn-danger btn-xs' %></td>
	 </tr>
	 <%end%>
</tbody>    
</table>

app/views/lists/destroy.js.erb
$('.delete_list').bind('ajax:success', function() {
   $(this).closest('tr').animate(1000);
});

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list, class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Back', lists_path, class: 'btn btn-warning btn-xs' %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Lists</h1>

<%= form_tag lists_path, :method => 'get', :id => "lists_search", :remote => :true do %>
  <p>
    <%= text_field_tag :search, params[:search], :id => 'lists_searchs' %>
    <%= submit_tag "Search", :name => nil, :class => 'searchs' %>
  </p>
<div id="lists"><%= render 'lists' %></div>
<% end %>
<%= will_paginate @lists, renderer: BootstrapPagination::Rails  %>
<div class="btns">
<%= link_to new_list_path, class: 'btn btn-success btn-xs' do %>
  <i class="glyphicon glyphicon-plus"></i> New List
<% end %>
<%= link_to 'Send Mail', send_email_path,  class: 'btn btn-warning btn-xs mail' %>
</div>

app/views/lists/index.js.erb
$("#lists").html("<%= escape_javascript(render("lists")) %>");

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form'  %>

<%= link_to 'Back', lists_path, class: 'btn btn-primary btn-xs' %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @list.text %>
</p>

<p>
  <strong>Price:</strong>
  <%= @list.price %>
</p>
  
<p>
  <strong>Quantity:</strong>
  <%= @list.quantity %>
</p>
<p>
  <strong>Photo:</strong>
   <%= image_tag @list.photo %>
</p>

<p>
  <strong>Vat:</strong>
  <%= @list.vat %>
</p>

<p>
  <strong>Total:</strong>
  <%= @list.total %>
</p>

<p>
  <strong>Product:</strong>
  <%= @list.product_id %>
</p>

<%= link_to 'Edit', edit_list_path(@list), class: 'btn btn-primary btn-xs' %> |
<%= link_to 'Back', lists_path, class: 'btn btn-warning btn-xs' %>

app/views/lists/show.js.erb
$('.show_list').bind('ajax:success', function() {
	
		alert("ehloos");
});